//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string Invoice_ID { get; set; }
        public string Patient_ID { get; set; }
        public int RN_Charge { get; set; }
        public int Doctor_Charge { get; set; }
        public int Prescription_Charge { get; set; }
        public int Lab_Charge { get; set; }
        public int Procedure_Charge { get; set; }
        public int No_of_days { get; set; }
        public string Provider_Group_No { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
