//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lab()
        {
            this.tbl_InPatient = new HashSet<tbl_InPatient>();
        }
    
        public string Lab_ID { get; set; }
        public string Doctor_ID { get; set; }
        public System.DateTime Lab_Date { get; set; }
        public string Patient_ID { get; set; }
        public int Invoice_Amount { get; set; }
        public string Lab_Procedure { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_InPatient> tbl_InPatient { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
