//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public string PR_Group_ID { get; set; }
        public string PR_Group_Name { get; set; }
        public string PR_Group_Address { get; set; }
    }
}
