//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InPatient
    {
        public string InPatient_ID { get; set; }
        public string Lab_ID { get; set; }
        public string Patient_Status { get; set; }
        public System.DateTime Admission_Date { get; set; }
        public System.DateTime Discharge_Time { get; set; }
        public string Room_ID { get; set; }
        public string Room_Type { get; set; }
        public string Room_Status { get; set; }
    
        public virtual Lab Lab { get; set; }
    }
}
